from event_core.domain.types import FileExt

THUMB_WIDTH = 300
THUMB_HEIGHT = 200

IMG_CHUNK_WIDTH = 400
IMG_CHUNK_HEIGHT = 400
IMG_EXT = FileExt.PNG

TEXT_CHUNK_SIZE = 300
TEXT_CHUNK_OVERLAP = 0
TEXT_CHUNK_MIN_SIZE = 50

PDF_X_CUTS = 1
PDF_Y_CUTS = 1
